language: python

sudo: required

python:
  - "2.7"

before_install:
  - cd app/

env:
  global:
    - SECRET_KEY="YOUR SECRET_KEY IN HERE BETWEEN THE QUOTES"
    - DB_NAME=INSERT A DB NAME
    - DB_USER=postgres
    - DB_PASS=""
    - DB_HOST=localhost
    - DB_PORT=""

services:
  - postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database SAME_DB_NAME_AS_ABOVE;' -U postgres

script: python manage.py test
